/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Apr 30 2026
 * Processor: PIC16F877A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include <stdio.h>

#pragma config FOSC = XT
#pragma config WDTE = OFF
#pragma config PWRTE = ON
#pragma config BOREN = ON
#pragma config LVP = OFF
#pragma config CPD = OFF
#pragma config WRT = OFF
#pragma config CP = OFF

#define _XTAL_FREQ 400000

void instCtrl (unsigned char INST)
{
	PORTB = INST;
	RD0 = 0;		// for instCtrl set RS to 0
	RD1 = 1;
	__delay_ms(1000);
	RD1 = 0;
}

void dataCtrl (unsigned char DATA)
{
	PORTB = DATA;
	RD0 = 1;		// for dataCtrl set RS to 1
	RD1 = 1;
	__delay_ms(1000);
	RD1 = 0;
}

void initLCD()
{
	__delay_ms(1000);	// LCD Startup
	instCtrl(0x38);		// function set: 8-bit; dual-line
	instCtrl(0x08);		// display off
	instCtrl(0x01);		// display clear
	instCtrl(0x06);		// entry mode: increment; shift off 
	instCtrl(0x0C);		// display on; cursor off; blink off
}

void init_I2C_Master(void)
{
	TRISC3 = 1;			// set RC3 (SCL) to input
	TRISC4 = 1;			// set RC4 (SDA) to input
	SSPCON = 0x28;		// SSP enabled, I2C master mode
	SSPCON2 = 0x00;		// start condition idle, stop condition idle
						// receive idle
	SSPSTAT = 0x00;		// slew rate enabled
	SSPADD = 0x09;		// clock frequency at 100 KHz (FOSC = 4MHz)
	
}

void I2C_Wait(void)
{
	/* wait until all I2C operation are finished */
	while ((SSPCON2 & 0x1F) || (SSPSTAT & 0x04));
}

void I2C_Start(void)
{
	/* wait until all I2C operation are finished */
	I2C_Wait();

	/* enable start condition */
	SEN = 1;	// SSPCON2	
}

void I2C_Stop(void)
{
	/* wait until all I2C operation are finished */
	I2C_Wait();
	
	/* enable stop condition */
	PEN = 1;	// SSPCON2
}

void I2C_RepeatedStart(void)
{
	/* wait until all I2C operation are finished */
	I2C_Wait();

	/* enable repeated start */
	RSEN = 1;	// SSPCON2
}

void I2C_Send(unsigned char data)
{
	/* wait until all I2C operation are finished */
	I2C_Wait();

	/* write data to buffer and transmit */
	SSPBUF = data;
}

unsigned char I2C_Receive(unsigned char ack)
{
	unsigned char temp;
	
	I2C_Wait();			// wait until all I2C operation are finished
	RCEN = 1;			// enable Receive (SSPCON2 reg)

	I2C_Wait();			// wait until all I2C operation are finished
	temp = SSPBUF;		// read SSP buffer

	I2C_Wait();			// wait until all I2C operation are finished
	ACKDT = (ack)?0:1;	// set acknowledge (ACK) or not acknowledge (NACK)
	ACKEN = 1;			// enable acknowledge sequence

	return temp;
}

void main(void)
 {
      TRISB = 0x00;
      TRISD = 0x00;
      PORTB = 0;
      PORTD = 0;
      initLCD();
      init_I2C_Master();	// initialize I2C as master
	
      instCtrl(0x80);
      dataCtrl('H');
      dataCtrl('u');
      dataCtrl('m');
      dataCtrl('i');
      dataCtrl('d');
      dataCtrl('i');
      dataCtrl('t');
      dataCtrl('y');
      dataCtrl(':');
      instCtrl(0xC0);
      dataCtrl('T');
      dataCtrl('e');
      dataCtrl('m');
      dataCtrl('p');
      dataCtrl('e');
      dataCtrl('r');
      dataCtrl('a');
      dataCtrl('t');
      dataCtrl('u');
      dataCtrl('r');
      dataCtrl('e');
      dataCtrl(':');
      while(1)
      {
	 unsigned int humidity, temperature, humidityMSB, humidityLSB, temperatureMSB, temperatureLSB;
	 char hum[8], temp[8];
	 float fhumidity, ftemperature;
	 
	 I2C_Start();
	 I2C_Send(0x80);
	 I2C_Send(0xE5);
	 I2C_RepeatedStart();
	 I2C_Send(0x81);
	 humidityMSB = I2C_Receive(1);
	 humidityLSB = I2C_Receive(0);
	 I2C_Stop();
	 
	 humidity = humidityMSB << 8;
	 humidity = humidity | (humidityLSB & 0xFC);
	 
	 fhumidity = -6.0 + 125.0 * (humidity / 65536.0);
	 
	 sprintf(hum, "%f", fhumidity);
         instCtrl(0x8A); // line 1
       
	 dataCtrl(hum[0]);
	 dataCtrl(hum[1]);
	 dataCtrl(hum[2]);
	 dataCtrl(hum[3]);
	 dataCtrl(hum[4]);
	 dataCtrl('%');
	 
	 I2C_Start();
	 I2C_Send(0x80);
	 I2C_Send(0xE3);
	 I2C_RepeatedStart();
	 I2C_Send(0x81);
	 temperatureMSB = I2C_Receive(1);
	 temperatureLSB = I2C_Receive(0);
	 I2C_Stop();
	 
	 temperature = temperatureMSB << 8;
	 temperature = temperature | (temperatureLSB & 0xFC);
	 
	 ftemperature = -46.85 + 175.72 * (temperature / 65536.0);
	 
	 
	 sprintf(temp, "%f", ftemperature);
         instCtrl(0xCC); // line 2
       
	 dataCtrl(temp[0]);
	 dataCtrl(temp[1]);
	 dataCtrl(temp[2]);
	 dataCtrl(temp[3]);
	 dataCtrl(temp[4]);
	 dataCtrl('C');
	 
	 
      }
 }
 